import Link from "next/link";
import type { Route } from "next";
import { ArrowLeft, CheckCircle2, LockKeyhole, RouteIcon } from "lucide-react";
import { LoginForm } from "@/features/auth/components/login-form";
import { resolveAuthenticatedRoute } from "@/features/auth/routes";

export default async function LoginPage({ searchParams }: PageProps<"/login">) {
  const returnTo = resolveAuthenticatedRoute((await searchParams).returnTo);
  return <main className="min-h-dvh bg-background px-5 py-6 sm:px-6 sm:py-8 lg:px-10 lg:py-10"><div className="mx-auto flex max-w-6xl flex-col lg:min-h-[calc(100dvh-5rem)]"><Link href={"/" as Route} className="hidden w-fit items-center gap-2 rounded-lg px-2 py-2 text-sm font-medium text-muted hover:bg-surface-muted hover:text-foreground lg:inline-flex"><ArrowLeft aria-hidden="true" size={16} /> Back to ATC project</Link><div className="grid flex-1 items-start lg:grid-cols-[minmax(0,1fr)_28rem] lg:items-center lg:gap-16 lg:py-10"><section aria-labelledby="access-heading" className="hidden max-w-xl lg:block"><div className="mb-8 grid size-12 place-items-center rounded-2xl bg-accent text-lg font-bold text-accent-foreground">A</div><p className="text-sm font-semibold text-accent">Workspace sign-in</p><h1 id="access-heading" className="mt-3 text-5xl font-semibold tracking-[-0.035em]">Sign in once, then get back to work.</h1><p className="mt-5 text-base leading-7 text-muted">Enter your work email and password. Aries verifies your sign-in, then takes you back to the page you wanted.</p><div className="mt-8 grid gap-4"><div className="flex gap-3"><LockKeyhole aria-hidden="true" className="mt-0.5 shrink-0 text-accent" size={19} /><div><p className="text-sm font-semibold">Use your own credentials</p><p className="mt-1 text-sm leading-6 text-muted">Your account and permissions are checked every time you sign in.</p></div></div><div className="flex gap-3"><RouteIcon aria-hidden="true" className="mt-0.5 shrink-0 text-accent" size={19} /><div><p className="text-sm font-semibold">We’ll take you back where you started</p><p className="mt-1 text-sm leading-6 text-muted">After signing in, you’ll return to the workspace page you requested.</p></div></div></div></section><section aria-labelledby="sign-in-heading" className="w-full max-w-md justify-self-center border-0 bg-transparent p-0 shadow-none sm:rounded-2xl sm:border sm:border-border sm:bg-surface sm:p-8 sm:shadow-sm lg:max-w-none"><div className="mb-8 flex items-center gap-3 lg:hidden"><div className="grid size-10 place-items-center rounded-xl bg-accent font-bold text-accent-foreground">A</div><div><p className="font-semibold tracking-tight">ATC project</p><p className="text-xs text-muted">Secure workspace access</p></div></div><div className="mb-7"><div className="hidden items-center gap-2 text-sm font-medium text-[var(--aries-success)] lg:flex"><CheckCircle2 aria-hidden="true" size={16} /> Secure sign-in</div><h2 id="sign-in-heading" className="text-3xl font-semibold tracking-tight lg:mt-3 lg:text-2xl">Sign in</h2><p className="mt-2 text-sm leading-6 text-muted">Enter your email and password to continue.</p></div><LoginForm returnTo={returnTo} /></section></div></div></main>;
}
