import Link from "next/link";
import type { Route } from "next";
import { ArrowLeft, CheckCircle2, LockKeyhole, RouteIcon } from "lucide-react";
import { LoginForm } from "@/features/auth/components/login-form";
import { resolveAuthenticatedRoute } from "@/features/auth/routes";

export default async function LoginPage({ searchParams }: PageProps<"/login">) {
  const returnTo = resolveAuthenticatedRoute((await searchParams).returnTo);
  return <main className="min-h-screen bg-background px-6 py-8 lg:px-10 lg:py-10"><div className="mx-auto flex min-h-[calc(100vh-4rem)] max-w-6xl flex-col"><Link href={"/" as Route} className="inline-flex w-fit items-center gap-2 rounded-lg px-2 py-2 text-sm font-medium text-muted hover:bg-surface-muted hover:text-foreground"><ArrowLeft aria-hidden="true" size={16} /> Back to ATC project</Link><div className="grid flex-1 items-center gap-10 py-10 lg:grid-cols-[minmax(0,1fr)_28rem] lg:gap-16"><section aria-labelledby="access-heading" className="max-w-xl"><div className="mb-8 grid size-12 place-items-center rounded-2xl bg-accent text-lg font-bold text-accent-foreground">A</div><p className="text-sm font-semibold text-accent">Workspace sign-in</p><h1 id="access-heading" className="mt-3 text-4xl font-semibold tracking-[-0.035em] sm:text-5xl">Sign in once, then get back to work.</h1><p className="mt-5 text-base leading-7 text-muted">Enter your work email and password. Aries verifies your sign-in, then takes you back to the page you wanted.</p><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-1"><div className="flex gap-3"><LockKeyhole aria-hidden="true" className="mt-0.5 shrink-0 text-accent" size={19} /><div><p className="text-sm font-semibold">Use your own credentials</p><p className="mt-1 text-sm leading-6 text-muted">Your account and permissions are checked every time you sign in.</p></div></div><div className="flex gap-3"><RouteIcon aria-hidden="true" className="mt-0.5 shrink-0 text-accent" size={19} /><div><p className="text-sm font-semibold">We’ll take you back where you started</p><p className="mt-1 text-sm leading-6 text-muted">After signing in, you’ll return to the workspace page you requested.</p></div></div></div></section><section aria-labelledby="sign-in-heading" className="rounded-2xl border border-border bg-surface p-7 shadow-sm sm:p-8"><div className="mb-7"><div className="flex items-center gap-2 text-sm font-medium text-[var(--aries-success)]"><CheckCircle2 aria-hidden="true" size={16} /> Secure sign-in</div><h2 id="sign-in-heading" className="mt-3 text-2xl font-semibold tracking-tight">Sign in</h2><p className="mt-2 text-sm leading-6 text-muted">Use your workspace credentials. You’ll choose an account when you start a transaction.</p></div><LoginForm returnTo={returnTo} /></section></div></div></main>;
}
